settings:
  title: 'Status Page'
  url: 'https://vagov-cf-statuspage.vagov-cf-statuspage.workers.dev/' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: vagov-va-gov
    name: va-gov
    url: 'https://www.va.gov'
    method: GET
    expectStatus: 200
    followRedirect: false

  - id: vagov-myhealth-va-gov
    name: myhealth-va-gov
    url: 'https://www.myhealth.va.gov/mhv-portal-web/home'
    method: GET
    expectStatus: 200
    followRedirect: false

  - id: vagov-ebenefits-va-gov
    name: ebenefits-va-gov
    url: 'https://www.ebenefits.va.gov/ebenefits/homepage'
    method: GET
    expectStatus: 200
    followRedirect: false

  - id: vagov-lgy-va-gov
    name: lgy-va-gov
    url: 'https://lgy.va.gov/lgyhub/'
    method: GET
    expectStatus: 200
    followRedirect: false

  - id: vagov-mobile-va-gov
    name: mobile-va-gov
    url: 'https://mobile.va.gov/'
    method: GET
    expectStatus: 200
    followRedirect: false

  - id: vagov-developer-va-gov
    name: developer-va-gov
    url: 'https://developer.va.gov/'
    method: GET
    expectStatus: 200
    followRedirect: false
