settings:
  title: 'Status Page'
  url: 'https://vagov-cf-statuspage.vagov-cf-statuspage.workers.dev/' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: vagov-va-gov
    name: vagov-va-gov-uptime-monitor
    description: 'The frontdoor of va.gov'
    url: 'https://www.va.gov' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false

  - id: vagov-myhealth-va-gov
    name: vagov-myhealth-va-gov-uptime-monitor
    description: 'A website for veterans health'
    url: 'https://www.myhealth.va.gov/mhv-portal-web/home'
    method: GET
    expectStatus: 200
    followRedirect: false

  - id: vagov-ebenefits-va-gov
    name: vagov-ebenefits-va-gov-uptime-monitor
    url: 'https://www.ebenefits.va.gov/ebenefits/homepage'
    method: GET
    expectStatus: 200
    followRedirect: false
