name = "vagov"
workers_dev = true
account_id = "41c979ec0c01c61c270c515c9b08fc59"
type = "webpack"
webpack_config = "node_modules/flareact/webpack"
kv_namespaces = [{binding="KV_STATUS_PAGE", id="57d99076edcc4a8396044fedb00c7c6f", preview_id=""}]

[triggers]
crons = ["*/1 * * * *"]

[site]
bucket = "out"
entry-point = "./"

[env.production]
kv_namespaces = [{binding="KV_STATUS_PAGE", id="57d99076edcc4a8396044fedb00c7c6f", preview_id=""}]
