name = "vagov"
type = "webpack"
account_id = "41c979ec0c01c61c270c515c9b08fc59"
workers_dev = true
webpack_config = "node_modules/flareact/webpack"

kv_namespaces = [{ binding = "KV_STATUS_PAGE", id="f48105fbcc2e4ae297c93d99165a2576" }]

[triggers]
crons = ["*/3 * * * *"]

[site]
bucket = "out"
entry-point = "./"

[env.production]
kv_namespaces = [{ binding="KV_STATUS_PAGE", id="f48105fbcc2e4ae297c93d99165a2576" }]
