name = "cf-workers-status-page"
workers_dev = true
account_id = ""
type = "webpack"
webpack_config = "node_modules/flareact/webpack"

kv-namespaces = [{binding="KV_STATUS_PAGE", id="xxxx", preview_id=""}]
zone_id="xxx"
route="xxx"

[triggers]
crons = ["* * * * *"]

[site]
bucket = "out"
entry-point = "./"
